// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj_oi2jkSMjOlBmn3BEpYHrg_CRFn6ud8',
    appId: '1:851845413646:web:2bf3ecefc9ff3c3ce9755f',
    messagingSenderId: '851845413646',
    projectId: 'worddown-app-9923',
    authDomain: 'worddown-app-9923.firebaseapp.com',
    storageBucket: 'worddown-app-9923.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiNB49V66CAxaiP_0UtX9yZSv1sw_9WJE',
    appId: '1:851845413646:android:cd2ec98f978bce33e9755f',
    messagingSenderId: '851845413646',
    projectId: 'worddown-app-9923',
    storageBucket: 'worddown-app-9923.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj_oi2jkSMjOlBmn3BEpYHrg_CRFn6ud8',
    appId: '1:851845413646:web:2def84cd4b27feeee9755f',
    messagingSenderId: '851845413646',
    projectId: 'worddown-app-9923',
    authDomain: 'worddown-app-9923.firebaseapp.com',
    storageBucket: 'worddown-app-9923.firebasestorage.app',
  );
}
