import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'services/encryption_service.dart';
import 'screens/login_screen.dart';
import 'package:google_fonts/google_fonts.dart';
import 'screens/home_screen.dart';
import 'services/database_service.dart';
import 'services/progress_service.dart';
import 'services/settings_service.dart';
import 'firebase_options.dart'; // Generated by flutterfire

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(WordDownApp());
}

class WordDownApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // This perfectly mimics the native Android 12 splash screen for a seamless transition
    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      body: Stack(
        alignment: Alignment.center,
        children: [
          // The logo exactly in the center, matching the Android system splash
          Center(
            child: ClipRRect(
              borderRadius: BorderRadius.circular(24),
              child: Image.asset(
                'assets/icon.png',
                width: 144, // Standard Android 12 splash icon size
                height: 144,
              ),
            ),
          ),
          // Loading spinner tucked at the bottom so it fades in cleanly
          Positioned(
            bottom: 60,
            child: CircularProgressIndicator(color: const Color(0xFF6366F1)),
          ),
        ],
      ),
    );
  }
}

class SplashLoadingScreen extends StatefulWidget {
  @override
  _SplashLoadingScreenState createState() => _SplashLoadingScreenState();
}

class _SplashLoadingScreenState extends State<SplashLoadingScreen> {
  @override
  void initState() {
    super.initState();
    _initializeApp();
  }

  Future<void> _initializeApp() async {
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    } catch (e) {
      print('Firebase initialization failed: ');
    }

    FirebaseAuth.instance.authStateChanges().listen((User? user) async {
      if (user == null) {
        if (mounted) {
          Navigator.of(context).pushReplacement(
            MaterialPageRoute(builder: (_) => LoginScreen()),
          );
        }
      } else {
        try {
          // Fetch keys from Firestore
          final doc = await FirebaseFirestore.instance.collection('config').doc('secrets').get();
          
          if (doc.exists && doc.data() != null) {
            final data = doc.data()!;
            final String key = data['key'];
            final String iv = data['iv'];
            
            EncryptionService.initialize(key, iv);
            
            await DatabaseService.init();
            await ProgressService().init();
            await SettingsService().init();

            if (mounted) {
              Navigator.of(context).pushReplacement(
                MaterialPageRoute(builder: (_) => HomeScreen()),
              );
            }
          } else {
            throw Exception('Secret keys not found in database.');
          }
        } catch (e) {
          print('Access Denied or Error: ');
          await FirebaseAuth.instance.signOut();
          if (mounted) {
             ScaffoldMessenger.of(context).showSnackBar(
               SnackBar(content: Text('Access Denied. You are not on the approved list.')),
             );
             Navigator.of(context).pushReplacement(
               MaterialPageRoute(builder: (_) => LoginScreen()),
             );
          }
        }
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    // This perfectly mimics the native Android 12 splash screen for a seamless transition
    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      body: Stack(
        alignment: Alignment.center,
        children: [
          // The logo exactly in the center, matching the Android system splash
          Center(
            child: ClipRRect(
              borderRadius: BorderRadius.circular(24),
              child: Image.asset(
                'assets/icon.png',
                width: 144, // Standard Android 12 splash icon size
                height: 144,
              ),
            ),
          ),
          // Loading spinner tucked at the bottom so it fades in cleanly
          Positioned(
            bottom: 60,
            child: CircularProgressIndicator(color: const Color(0xFF6366F1)),
          ),
        ],
      ),
    );
  }
}
