import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'services/encryption_service.dart';
import 'screens/login_screen.dart';
import 'package:google_fonts/google_fonts.dart';
import 'screens/home_screen.dart';
import 'services/database_service.dart';
import 'services/progress_service.dart';
import 'services/settings_service.dart';
import 'services/media_cache_service.dart';
import 'firebase_options.dart'; // Generated by flutterfire

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(WordDownApp());
}

class WordDownApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'word down',
      themeMode: ThemeMode.dark,
      darkTheme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color(0xFF0F172A),
        primaryColor: const Color(0xFF6366F1),
        colorScheme: const ColorScheme.dark(
          primary: Color(0xFF6366F1),
          secondary: Color(0xFF8B5CF6),
          surface: Color(0xFF1E293B),
        ),
        textTheme: GoogleFonts.outfitTextTheme(ThemeData.dark().textTheme),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.transparent,
          elevation: 0,
          centerTitle: true,
        ),
        cardTheme: CardThemeData(
          color: const Color(0xFF1E293B),
          elevation: 8,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        ),
      ),
      home: SplashLoadingScreen(),
    );
  }
}

class SplashLoadingScreen extends StatefulWidget {
  @override
  _SplashLoadingScreenState createState() => _SplashLoadingScreenState();
}

class _SplashLoadingScreenState extends State<SplashLoadingScreen> {
  @override
  void initState() {
    super.initState();
    _initializeApp();
  }

  Future<void> _initializeApp() async {
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    } catch (e) {
      print('Firebase initialization failed: ');
    }

    FirebaseAuth.instance.authStateChanges().listen((User? user) async {
      if (user == null) {
        if (mounted) {
          Navigator.of(context).pushReplacement(
            MaterialPageRoute(builder: (_) => LoginScreen()),
          );
        }
      } else {
        // 1. Try loading cached keys first for instant offline availability
        await EncryptionService.loadFromLocalStorage();

        bool onlineSuccess = false;
        try {
          // Attempt to fetch fresh keys from Firestore with a 4s timeout
          final doc = await FirebaseFirestore.instance
              .collection('config')
              .doc('secrets')
              .get()
              .timeout(const Duration(seconds: 4));
          
          if (doc.exists && doc.data() != null) {
            final data = doc.data()!;
            final String key = data['key'];
            final String iv = data['iv'];
            
            // Persist locally for offline launches
            await EncryptionService.saveToLocalStorage(key, iv);
            onlineSuccess = true;
          } else {
            throw Exception('Secret keys not found in database.');
          }
        } catch (e) {
          print('Key fetch note/error: $e');
          final errStr = e.toString().toLowerCase();

          // Explicit permission denied -> Access was revoked on Firebase
          if (errStr.contains('permission-denied')) {
            await EncryptionService.clearLocalStorage();
            await FirebaseAuth.instance.signOut();
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Access Denied. You are not on the approved list.')),
              );
              Navigator.of(context).pushReplacement(
                MaterialPageRoute(builder: (_) => LoginScreen()),
              );
            }
            return;
          }
        }

        // 2. If online succeeded or we have valid cached offline keys, proceed!
        if (onlineSuccess || EncryptionService.isInitialized) {
          await DatabaseService.init();
          await ProgressService().init();
          await SettingsService().init();
          await MediaCacheService.getAppDocsPath();

          if (mounted) {
            Navigator.of(context).pushReplacement(
              MaterialPageRoute(builder: (_) => HomeScreen()),
            );
          }
        } else {
          // Offline and no cached keys found (e.g. first launch without network/VPN)
          await FirebaseAuth.instance.signOut();
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Connection error fetching keys. Please check your VPN/internet connection.')),
            );
            Navigator.of(context).pushReplacement(
              MaterialPageRoute(builder: (_) => LoginScreen()),
            );
          }
        }
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    // This perfectly mimics the native Android 12 splash screen for a seamless transition
    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      body: Stack(
        alignment: Alignment.center,
        children: [
          // The logo exactly in the center, matching the Android system splash
          Center(
            child: ClipRRect(
              borderRadius: BorderRadius.circular(24),
              child: Image.asset(
                'assets/icon.png',
                width: 144, // Standard Android 12 splash icon size
                height: 144,
              ),
            ),
          ),
          // Loading spinner tucked at the bottom so it fades in cleanly
          Positioned(
            bottom: 60,
            child: CircularProgressIndicator(color: const Color(0xFF6366F1)),
          ),
        ],
      ),
    );
  }
}
