import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'services/encryption_service.dart';
import 'screens/login_screen.dart';
import 'package:google_fonts/google_fonts.dart';
import 'screens/home_screen.dart';
import 'services/database_service.dart';
import 'services/progress_service.dart';
import 'services/settings_service.dart';
import 'services/media_cache_service.dart';
import 'services/wordup_api.dart';
import 'services/sync_service.dart';
import 'firebase_options.dart'; // Generated by flutterfire

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(WordDownApp());
}

class WordDownApp extends StatefulWidget {
  @override
  State<WordDownApp> createState() => _WordDownAppState();
}

class _WordDownAppState extends State<WordDownApp> {
  late final AppLifecycleListener _lifecycleListener;

  @override
  void initState() {
    super.initState();
    _lifecycleListener = AppLifecycleListener(
      onExitRequested: () async {
        if (SyncService().isSyncing.value) {
          debugPrint('App exit requested while sync active; waiting up to 3s for clean completion...');
          await SyncService().waitForSyncToComplete(const Duration(seconds: 3));
        }
        return AppExitResponse.exit;
      },
    );
  }

  @override
  void dispose() {
    _lifecycleListener.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'word down',
      themeMode: ThemeMode.dark,
      darkTheme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color(0xFF0F172A),
        primaryColor: const Color(0xFF6366F1),
        colorScheme: const ColorScheme.dark(
          primary: Color(0xFF6366F1),
          secondary: Color(0xFF8B5CF6),
          surface: Color(0xFF1E293B),
        ),
        textTheme: GoogleFonts.outfitTextTheme(ThemeData.dark().textTheme),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.transparent,
          elevation: 0,
          centerTitle: true,
        ),
        cardTheme: CardThemeData(
          color: const Color(0xFF1E293B),
          elevation: 8,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        ),
      ),
      home: SplashLoadingScreen(),
    );
  }
}

class SplashLoadingScreen extends StatefulWidget {
  @override
  _SplashLoadingScreenState createState() => _SplashLoadingScreenState();
}

class _SplashLoadingScreenState extends State<SplashLoadingScreen> {
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _initializeApp();
  }

  Future<void> _initializeApp() async {
    if (mounted) {
      setState(() {
        _errorMessage = null;
      });
    }

    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    } catch (e) {
      debugPrint('Firebase initialization note: $e');
    }

    // 1. Try loading cached keys first for instant offline availability
    await EncryptionService.loadFromLocalStorage();

    // 2. Check current authenticated user.
    // On Windows desktop, persisted credentials may take a brief moment to hydrate from disk.
    User? user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      try {
        user = await FirebaseAuth.instance
            .authStateChanges()
            .firstWhere((u) => u != null)
            .timeout(const Duration(milliseconds: 1500));
      } catch (_) {
        user = FirebaseAuth.instance.currentUser;
      }
    }

    if (user == null) {
      if (mounted) {
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(builder: (_) => LoginScreen()),
        );
      }
      return;
    }

    // 3. User is authenticated. Attempt to fetch fresh keys from Firestore with an 8s timeout.
    bool onlineSuccess = false;
    try {
      final doc = await FirebaseFirestore.instance
          .collection('config')
          .doc('secrets')
          .get()
          .timeout(const Duration(seconds: 8));

      if (doc.exists && doc.data() != null) {
        final data = doc.data()!;
        final String? key = data['key'];
        final String? iv = data['iv'];

        if (key != null && iv != null) {
          await EncryptionService.saveToLocalStorage(key, iv);
          onlineSuccess = true;
        }
      }
    } catch (e) {
      debugPrint('Key fetch note/error (proceeding offline if cached): $e');
      // Invariant: NEVER signOut() or clearLocalStorage() automatically on network errors,
      // timeouts, or temporary token refresh delays!
    }

    // 4. If online succeeded or valid cached offline keys exist, enter the app!
    if (onlineSuccess || EncryptionService.isInitialized) {
      await DatabaseService.init();
      await ProgressService().init();
      await SettingsService().init();
      await MediaCacheService.getAppDocsPath();
      WordupApi.purgeLegacyTtsCache();

      if (mounted) {
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(builder: (_) => HomeScreen()),
        );
      }
    } else {
      // Offline on a fresh install without cached keys
      if (mounted) {
        setState(() {
          _errorMessage =
              'Could not connect to verify decryption keys.\nPlease check your internet connection or VPN and retry.';
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    // This perfectly mimics the native Android 12 splash screen for a seamless transition
    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      body: Stack(
        alignment: Alignment.center,
        children: [
          // The logo exactly in the center, matching the Android system splash
          Center(
            child: ClipRRect(
              borderRadius: BorderRadius.circular(24),
              child: Image.asset(
                'assets/icon.png',
                width: 144, // Standard Android 12 splash icon size
                height: 144,
              ),
            ),
          ),
          // Bottom area: Error/Retry UI or standard loading spinner
          Positioned(
            bottom: 60,
            left: 24,
            right: 24,
            child: _errorMessage != null
                ? Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: const Color(0xFF1E293B),
                      borderRadius: BorderRadius.circular(16),
                      border: Border.all(color: Colors.redAccent.withAlpha(100)),
                    ),
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Text(
                          _errorMessage!,
                          textAlign: TextAlign.center,
                          style: const TextStyle(color: Colors.white70, fontSize: 14),
                        ),
                        const SizedBox(height: 16),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            ElevatedButton.icon(
                              onPressed: _initializeApp,
                              icon: const Icon(Icons.refresh, size: 18),
                              label: const Text('Retry'),
                              style: ElevatedButton.styleFrom(
                                backgroundColor: const Color(0xFF6366F1),
                                foregroundColor: Colors.white,
                              ),
                            ),
                            const SizedBox(width: 12),
                            TextButton(
                              onPressed: () async {
                                final nav = Navigator.of(context);
                                await FirebaseAuth.instance.signOut();
                                if (mounted) {
                                  nav.pushReplacement(
                                    MaterialPageRoute(builder: (_) => LoginScreen()),
                                  );
                                }
                              },
                              child: const Text('Switch Account', style: TextStyle(color: Colors.white54)),
                            ),
                          ],
                        ),
                      ],
                    ),
                  )
                : const Center(
                    child: CircularProgressIndicator(color: Color(0xFF6366F1)),
                  ),
          ),
        ],
      ),
    );
  }
}
